### Afficher toutes les classes
GET http://localhost:8080/api/classes
Accept: application/json

### Afficher une classe par ID
GET http://localhost:8080/api/classes/1
Accept: application/json

### Ajouter une classe
POST http://localhost:8080/api/classes
content-type: application/json

{
  "libelle": "L2 DWM",
  "filiereId": 1,
  "niveauId": 2
}

### Mettre à jour une classe existante
PUT http://localhost:8080/api/classes/3
content-type: application/json

{
    "libelle": "L1 DN",
    "filiereId": 3,
    "niveauId": 1
}

### Supprimer une classe existante
DELETE http://localhost:8080/api/classes/3
Accept: application/json