### Afficher tous les cours
GET http://localhost:4000/api/cours
Accept: application/json

### Afficher un cours par ID
GET http://localhost:4000/api/cours/1
Accept: application/json

### Ajouter un cours
POST http://localhost:4000/api/cours
Content-Type: application/json

{
  "dateCours": "2024-08-17 10:00",
  "duree": 180,
  "classeId": 1,
  "moduleId": 1
}

### Mettre à jour un cours
PUT http://localhost:4000/api/cours/5
Content-Type: application/json

{
  "dateCours": "2024-08-17 10:00",
  "duree": 180,
  "classeId": 1,
  "moduleId": 1
}

### Supprimer un cours
DELETE http://localhost:4000/api/cours/3
Accept: application/json
