### Afficher toutes les filieres
GET http://localhost:4000/api/filieres
Accept: application/json

### Afficher une filiere par ID
GET http://localhost:4000/api/filieres/2
Accept: application/json

### Ajouter une filiere
POST http://localhost:4000/api/filieres
Content-Type: application/json

{
  "libelle": "MD"
}

### Modifier une filiere existante
PUT http://localhost:4000/api/filieres/5
Content-Type: application/json

{
  "libelle": "MCD"
}

### Supprimer une filiere existante
DELETE http://localhost:4000/api/filieres/5
Accept: application/json
