### Afficher toutes les filieres
GET http://localhost:8080/api/filieres
Accept: application/json

### Afficher une filiere par ID
GET http://localhost:8080/api/filieres/2
Accept: application/json

### Ajouter une filiere
POST http://localhost:8080/api/filieres
Content-Type: application/json

{
  "libelle": "DN"
}

### Modifier une filiere existante
PUT http://localhost:8080/api/filieres/4
Content-Type: application/json

{
  "libelle": "MCD"
}

### Supprimer une filiere existante
DELETE http://localhost:8080/api/filieres/4
Accept: application/json
