### Afficher tous les modules
GET http://localhost:4000/api/modules
Accept: application/json

### Afficher un module par ID
GET http://localhost:4000/api/modules/1
Accept: application/json

### Ajouter un module
POST http://localhost:4000/api/modules
Content-Type: application/json

{
  "libelle": "SQL"
}

### Modifier un module existant
PUT http://localhost:4000/api/modules/2
Content-Type: application/json

{
  "libelle": "MongoDB"
}

### Supprimer un module existant
DELETE http://localhost:4000/api/modules/
Accept: application/json