### Afficher tous les niveaux
GET http://localhost:8080/api/niveaux
Accept: application/json

### Afficher un niveau par ID
GET http://localhost:8080/api/niveaux/1
Accept: application/json

### Ajouter un niveau
POST http://localhost:8080/api/niveaux
Content-Type: application/json

{
  "libelle": "M1"
}

### Modifier un niveau existant
PUT http://localhost:8080/api/niveaux/4
Content-Type: application/json

{
  "libelle": "M2"
}

### Supprimer un niveau existant
DELETE http://localhost:8080/api/niveaux/4
Accept: application/json